# This is a basic workflow to help you get started with Actions

name: staging

on:
  workflow_dispatch:

jobs:  
  calls-events-all-functions-deploy:
    runs-on: ubuntu-latest
    environment:
      name: staging
    steps:
      - name: Run a one-line script
        run: echo sls deploy -s staging
      
  calls-events-calls-aggregator-deploy:
    runs-on: ubuntu-latest
    environment:
      name: staging
    steps:
      - name: Run a one-line script
        run: echo sls deploy -s staging -f calls-aggregator
  
  calls-events-cdr-to-es-deploy:
    runs-on: ubuntu-latest
    environment:
      name: staging
    steps:
      - name: Run a one-line script
        run: echo sls deploy -s staging -f cdr-to-es
