# This is a basic workflow to help you get started with Actions

name: calls-events

on:
  workflow_dispatch:
    inputs:
      stage:
        description: 'Stage'
        required: true
        default: 'staging'
      function:
        description: 'Function Name'
        required: false
        default: ''

jobs:  
  calls-events:
    runs-on: ubuntu-latest
    environment:
      name: ${{ github.event.inputs.stage }}
    steps:
      - name: Run a one-line script
        run: echo sls deploy -s staging -f ${{ github.event.inputs.function }}
